version: "3.5"

services:
  # wordpressの設定
  wordpress:
    # コンテナ名を指定
    container_name: wp_docker
    # wordpressのイメージを指定(常に最新にする)
    image: wordpress:latest
    # ホストマシンのポート番号:コンテナのポート番号
    ports:
      - "9000:80"
    # ホスト側のテーマ開発ディレクトリをマウントする
    volumes:
      # ホスト側のパス:コンテナ側のパス
      - ~/Documents/workspace/blogtheme:/var/www/html/wp-content/themes/blogtheme
    # DBと連携する
    links:
      - wordpress-db
    environment:
      WORDPRESS_DB_HOST: "wordpress-db:3306"
    # git管理下に含めない環境設定ファイルを参照
    env_file: .env

  # wordpressで利用するDBの設定
  wordpress-db:
    # コンテナ名を指定
    container_name: db_docker
    # mysqlのイメージを指定(さくらのレンタルサーバと同じバージョン)
    image: mysql:5.7
    ports:
      - "3306:3306"
    # git管理下に含めない環境設定ファイルを参照
    env_file: .env
